import Head from 'next/head'
import { useState } from 'react';
import NavBar from './src/NavBar';
import Mainbody from './src/Mainbody';
import Myservice from './src/Myservice';
import Footer from './src/Footer';
import Contact from './contact/index';


export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  const title: string = "Blerch";

  return (
    <div className={darkMode ? "dark": ""}>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon"  href="/akyimagic.png" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link href="https://fonts.googleapis.com/css2?family=Abril+Fatface&family=Dancing+Script&family=Great+Vibes&family=Poppins&display=swap" rel="stylesheet" />

      </Head>
      <main className="bg-black dark:bg-gray-800">
        <NavBar darkMode={darkMode} setDarkMode={setDarkMode} title={title} />
        <div>
          <Mainbody />
          <Myservice />
          <Contact />
          <Footer title={title} />
        </div>
      </main>
    </div>
  )
}
