import Head from 'next/head'
import Homepage from './src/Homepage'

export default function Home() {
  return (
    <div>
      <Head>
        <title>My Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto">
         <h1>Comming soon</h1>
      </main>
    </div>
  )
}
