import Head from 'next/head'
import { AiFillTwitterCircle, AiFillLinkedin, AiFillGithub} from "react-icons/ai"
import Image from 'next/image';
import deved from "../public/dev-ed-wave.png";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import { useState } from 'react';
import NavBar from './src/NavBar';



export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark": ""}>
      <Head>
        <title>My Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 dark:bg-gray-800">
         <section className="min-h-screen">
          
          <NavBar darkMode={darkMode} setDarkMode={setDarkMode} />

            <div className="text-center p-10">
              <h2 className="text-5xl py-2 text-teal-500 font-medium">Kwame Ato</h2>
              <h3 className="text-2xl py-2 dark:text-white">Developer and designer</h3>

              <p className="text-md py-5 leading-8 text-gray-800 dark:text-white">
                Freelance providing services for programming needs.
                Read further to know more about me and what I do.
              </p>
            </div>

            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-500 dark:text-white">
                <a href="https://twitter.com/kwamea236"> <AiFillTwitterCircle /> </a>
                <a> <AiFillLinkedin className="cursor-pointer" /> </a>
                <a href="https://github.com/kwamea236"> <AiFillGithub /> </a>
            </div>

            <div className="relative bg-cyan-400 rounded-full mx-auto w-80 h-80 mt-20 overflow-hidden items-center">
               <Image src={deved} className="object-cover" />
            </div>

         </section>

         <section>
            <div>
              <div className="lg:text-center">
                <h3 className="text-3xl py-1 pt-5 dark:text-white">Services I offer</h3>
                <p className="text-md py-2 leading-8 text-gray-800 lg:mx-auto dark:text-white">
                Since the begining of my journey as a freelance web Developer,
                I've done remote work for <span className="text-cyan-500">agencies</span> and 
                collaborated with talented people to create digital product for 
                both business and consumer use.
                </p>

                <p className="text-md py-2 leading-8 text-gray-800 dark:text-white">
                  I am very passionate about the Javascript programming language,
                  but asside that I also know a couple of other programming languages
                  which are <span className="text-md font-bold text-cyan-500">C++, Java and PHP</span>.
                </p>
              </div>

              {/**
               * Cards designing stage
               */}

              <div className="lg:flex gap-10">
                <div className="text-center shadow p-10 rounded-2xl mt-10 dark:bg-white">
                    <Image src={design} width={100} height={100} className="mx-auto lg:mx-auto md:mx-auto" />
                    <h3 className="text-lg font-medium pt-8 pb-2">Beautiful Designs</h3>
                    <p className="py-2 leading-8">
                    Creating super elegant for your needs following cove
                    programming principles
                    </p>
                    <h4 className="pt-5 pb-3 text-teal-500">Design tools I used</h4>
                    <p className="text-gray-800 py-1">Figma</p>
                    <p className="text-gray-800 py-1">Javascript</p>
                    <p className="text-gray-800 py-1">Tailwind</p>
                </div>

                <div className="text-center shadow p-10 rounded-2xl mt-10 dark:bg-white">
                    <Image src={code} width={100} height={100} className="mx-auto lg:mx-auto md:mx-auto" />
                    <h3 className="text-lg font-medium pt-8 pb-2">Beautiful Designs</h3>
                    <p className="py-2 leading-8">
                    Creating super elegant for your needs following cove
                    programming principles
                    </p>
                    <h4 className="pt-5 pb-3 text-teal-500">Design tools I used</h4>
                    <p className="text-gray-800 py-1">Figma</p>
                    <p className="text-gray-800 py-1">Javascript</p>
                    <p className="text-gray-800 py-1">Tailwind</p>
                </div>

                <div className="text-center shadow p-10 rounded-2xl mt-10 dark:bg-white">
                    <Image src={consulting} width={100} height={100} className="mx-auto lg:mx-auto md:mx-auto" />
                    <h3 className="text-lg font-medium pt-8 pb-2">Beautiful Designs</h3>
                    <p className="py-2 leading-8">
                    Creating super elegant for your needs following cove
                    programming principles
                    </p>
                    <h4 className="pt-5 pb-3 text-teal-500">Design tools I used</h4>
                    <p className="text-gray-800 py-1">Figma</p>
                    <p className="text-gray-800 py-1">Javascript</p>
                    <p className="text-gray-800 py-1">Tailwind</p>
                </div>
              </div>
            </div>
         </section>

         <section>
          <div>
            <h3 className="text-3xl py-4 dark:text-white">Portfolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-white">
                More to come
              </p>
          </div>
         </section>
      </main>
    </div>
  )
}
